<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;

class StudentsSeeder extends Seeder
{
    public function run(): void
    {
        $students = [
            // Grade 1 Students (Age 6-7)
            [
                'admission_no' => 'ADM2024001',
                'first_name' => 'Emma',
                'middle_name' => 'Grace',
                'last_name' => 'Johnson',
                'date_of_birth' => '2017-03-15',
                'gender' => 'female',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0101',
                'emergency_contact' => '555-9101',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/emma_johnson.jpg',
                'status' => 'active',
            ],
            [
                'admission_no' => 'ADM2024002',
                'first_name' => 'Liam',
                'middle_name' => 'Alexander',
                'last_name' => 'Martinez',
                'date_of_birth' => '2017-07-22',
                'gender' => 'male',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0102',
                'emergency_contact' => '555-9102',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/liam_martinez.jpg',
                'status' => 'active',
            ],
            [
                'admission_no' => 'ADM2024003',
                'first_name' => 'Olivia',
                'middle_name' => 'Rose',
                'last_name' => 'Brown',
                'date_of_birth' => '2016-11-08',
                'gender' => 'female',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0103',
                'emergency_contact' => '555-9103',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/olivia_brown.jpg',
                'status' => 'active',
            ],
            
            // Grade 2 Students (Age 7-8)
            [
                'admission_no' => 'ADM2024004',
                'first_name' => 'Noah',
                'middle_name' => 'James',
                'last_name' => 'Davis',
                'date_of_birth' => '2016-01-20',
                'gender' => 'male',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0104',
                'emergency_contact' => '555-9104',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/noah_davis.jpg',
                'status' => 'active',
            ],
            [
                'admission_no' => 'ADM2024005',
                'first_name' => 'Ava',
                'middle_name' => 'Elizabeth',
                'last_name' => 'Wilson',
                'date_of_birth' => '2016-05-12',
                'gender' => 'female',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0105',
                'emergency_contact' => '555-9105',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/ava_wilson.jpg',
                'status' => 'active',
            ],
            [
                'admission_no' => 'ADM2024006',
                'first_name' => 'Ethan',
                'middle_name' => 'Michael',
                'last_name' => 'Garcia',
                'date_of_birth' => '2016-09-03',
                'gender' => 'male',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0106',
                'emergency_contact' => '555-9106',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/ethan_garcia.jpg',
                'status' => 'active',
            ],
            
            // Grade 3 Students (Age 8-9)
            [
                'admission_no' => 'ADM2024007',
                'first_name' => 'Sophia',
                'middle_name' => 'Marie',
                'last_name' => 'Rodriguez',
                'date_of_birth' => '2015-02-28',
                'gender' => 'female',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0107',
                'emergency_contact' => '555-9107',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/sophia_rodriguez.jpg',
                'status' => 'active',
            ],
            [
                'admission_no' => 'ADM2024008',
                'first_name' => 'Mason',
                'middle_name' => 'William',
                'last_name' => 'Lewis',
                'date_of_birth' => '2015-06-15',
                'gender' => 'male',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0108',
                'emergency_contact' => '555-9108',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/mason_lewis.jpg',
                'status' => 'active',
            ],
            [
                'admission_no' => 'ADM2024009',
                'first_name' => 'Isabella',
                'middle_name' => 'Nicole',
                'last_name' => 'Lee',
                'date_of_birth' => '2015-10-07',
                'gender' => 'female',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0109',
                'emergency_contact' => '555-9109',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/isabella_lee.jpg',
                'status' => 'active',
            ],
            
            // Grade 4 Students (Age 9-10)
            [
                'admission_no' => 'ADM2024010',
                'first_name' => 'William',
                'middle_name' => 'Thomas',
                'last_name' => 'Walker',
                'date_of_birth' => '2014-04-12',
                'gender' => 'male',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0110',
                'emergency_contact' => '555-9110',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/william_walker.jpg',
                'status' => 'active',
            ],
            [
                'admission_no' => 'ADM2024011',
                'first_name' => 'Mia',
                'middle_name' => 'Catherine',
                'last_name' => 'Hall',
                'date_of_birth' => '2014-08-20',
                'gender' => 'female',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0111',
                'emergency_contact' => '555-9111',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/mia_hall.jpg',
                'status' => 'active',
            ],
            [
                'admission_no' => 'ADM2024012',
                'first_name' => 'James',
                'middle_name' => 'Robert',
                'last_name' => 'Allen',
                'date_of_birth' => '2014-12-05',
                'gender' => 'male',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0112',
                'emergency_contact' => '555-9112',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/james_allen.jpg',
                'status' => 'active',
            ],
            
            // Grade 5 Students (Age 10-11)
            [
                'admission_no' => 'ADM2024013',
                'first_name' => 'Charlotte',
                'middle_name' => 'Anne',
                'last_name' => 'Young',
                'date_of_birth' => '2013-01-30',
                'gender' => 'female',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0113',
                'emergency_contact' => '555-9113',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/charlotte_young.jpg',
                'status' => 'active',
            ],
            [
                'admission_no' => 'ADM2024014',
                'first_name' => 'Benjamin',
                'middle_name' => 'David',
                'last_name' => 'Hernandez',
                'date_of_birth' => '2013-05-18',
                'gender' => 'male',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0114',
                'emergency_contact' => '555-9114',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/benjamin_hernandez.jpg',
                'status' => 'active',
            ],
            [
                'admission_no' => 'ADM2024015',
                'first_name' => 'Amelia',
                'middle_name' => 'Jane',
                'last_name' => 'King',
                'date_of_birth' => '2013-09-22',
                'gender' => 'female',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0115',
                'emergency_contact' => '555-9115',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/amelia_king.jpg',
                'status' => 'active',
            ],
            
            // Alumni Students
            [
                'admission_no' => 'ADM2023001',
                'first_name' => 'Alexander',
                'middle_name' => 'James',
                'last_name' => 'Wright',
                'date_of_birth' => '2011-06-15',
                'gender' => 'male',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0201',
                'emergency_contact' => '555-9201',
                'admission_date' => '2022-09-01',
                'photo_url' => 'students/alexander_wright.jpg',
                'status' => 'alumni',
            ],
            [
                'admission_no' => 'ADM2023002',
                'first_name' => 'Elizabeth',
                'middle_name' => 'Marie',
                'last_name' => 'Lopez',
                'date_of_birth' => '2011-02-20',
                'gender' => 'female',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0202',
                'emergency_contact' => '555-9202',
                'admission_date' => '2022-09-01',
                'photo_url' => 'students/elizabeth_lopez.jpg',
                'status' => 'alumni',
            ],
            
            // Transferred Students
            [
                'admission_no' => 'ADM2024004',
                'first_name' => 'Michael',
                'middle_name' => 'Ryan',
                'last_name' => 'Hill',
                'date_of_birth' => '2015-07-10',
                'gender' => 'male',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0203',
                'emergency_contact' => '555-9203',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/michael_hill.jpg',
                'status' => 'transferred',
            ],
            
            // Inactive Student
            [
                'admission_no' => 'ADM2024005',
                'first_name' => 'Sofia',
                'middle_name' => 'Isabella',
                'last_name' => 'Green',
                'date_of_birth' => '2014-12-18',
                'gender' => 'female',
                'city' => 'Springfield',
                'country' => 'USA',
                'phone' => '555-0204',
                'emergency_contact' => '555-9204',
                'admission_date' => '2024-09-01',
                'photo_url' => 'students/sofia_green.jpg',
                'status' => 'inactive',
            ],
        ];

        foreach ($students as $data) {
            Student::firstOrCreate(
                ['admission_no' => $data['admission_no']],
                $data
            );
        }
    }
}