<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Links purchase orders to the requisition they came from.
 *
 * The column is nullable: purchase orders created directly (walk-in purchases
 * that never went through a requisition) have no source document. Every PO
 * generated by RequisitionApprovalService records its requisition here, so the
 * audit chain requisition → PO → goods received is queryable.
 *
 * Existing rows are unaffected; the rollback drops the column and its index.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (Schema::hasColumn('purchase_orders', 'requisition_id')) {
            return;
        }

        Schema::table('purchase_orders', function (Blueprint $table) {
            $table->unsignedInteger('requisition_id')->nullable()->after('po_number');
            $table->index('requisition_id', 'purchase_orders_requisition_id_index');
        });

        // FK is added separately so an orphaned legacy row (should none exist)
        // cannot block the deploy; clean data passes the constraint below.
        $orphans = DB::table('purchase_orders')
            ->leftJoin('requisitions', 'requisitions.requisition_id', '=', 'purchase_orders.requisition_id')
            ->whereNotNull('purchase_orders.requisition_id')
            ->whereNull('requisitions.requisition_id')
            ->count();

        if ($orphans === 0) {
            Schema::table('purchase_orders', function (Blueprint $table) {
                $table->foreign('requisition_id', 'purchase_orders_requisition_fk')
                    ->references('requisition_id')->on('requisitions')
                    ->onDelete('set null');
            });
        }
    }

    public function down(): void
    {
        if (! Schema::hasColumn('purchase_orders', 'requisition_id')) {
            return;
        }

        Schema::table('purchase_orders', function (Blueprint $table) {
            $table->dropForeign('purchase_orders_requisition_fk');
            $table->dropIndex('purchase_orders_requisition_id_index');
            $table->dropColumn('requisition_id');
        });
    }
};
