<?php

namespace App\Http\Controllers;

use Flash;
use App\Models\Exam;
use App\Models\Subject;
use App\Models\SchoolClass;
use App\Models\ExamSchedule;
use Illuminate\Http\Request;
use App\Http\Controllers\AppBaseController;
use App\Repositories\ExamScheduleRepository;
use App\Models\AuditTrail;
use App\Http\Requests\CreateExamScheduleRequest;
use App\Http\Requests\UpdateExamScheduleRequest;
use Illuminate\Support\Facades\DB;

class ExamScheduleController extends AppBaseController
{
    /** @var ExamScheduleRepository $examScheduleRepository*/
    private $examScheduleRepository;

    public function __construct(ExamScheduleRepository $examScheduleRepo)
    {
        $this->examScheduleRepository = $examScheduleRepo;
        $this->middleware('can:academics.settings.manage')->only(['index', 'show', 'create', 'store', 'edit', 'update', 'destroy']);
    }

    /**
     * Display a listing of the ExamSchedule.
     */
    public function index(Request $request)
    {
        $examId = $request->get('exam_id');
        $exams = Exam::pluck('name', 'exam_id');
        $selectedExam = null;

        if ($examId) {
            $selectedExam = Exam::with(['examSchedules.subject', 'examSchedules.class'])->find($examId);
            $examSchedules = $selectedExam->examSchedules()->paginate(50);
        } else {
            $examSchedules = $this->examScheduleRepository->paginate(15);
        }

        return view('exam_schedules.index', compact('examSchedules', 'exams', 'selectedExam', 'examId'));
    }

    private function getDropdownData()
    {
        return [
            'exams' => \App\Models\Exam::pluck('name', 'exam_id'),
            'classes' => \App\Models\SchoolClass::pluck('name', 'class_id'),
            'subjects' => \App\Models\Subject::pluck('name', 'subject_id'),
            'rooms' => \App\Models\Classroom::pluck('room_number', 'classroom_id'),
        ];
    }
    /**
     * Show the form for creating a new ExamSchedule.
     */
    public function create()
    {
        $dropdownData = $this->getDropdownData();
        return view('exam_schedules.create', $dropdownData);
    }

    /**
     * Show the auto-generation form.
     *
     * Step 1: pick the exam. Step 2 (same page, after ?exam_id=): pick
     * which classes/subjects to include and the session parameters.
     */
    public function autoGenerate(Request $request)
    {
        $exams = Exam::orderByDesc('exam_id')->get(['exam_id', 'name', 'start_date', 'end_date', 'academic_year_id']);
        $selectedExamId = $request->get('exam_id');

        $classes = collect();
        $subjects = collect();

        if ($selectedExamId) {
            $exam = Exam::find($selectedExamId);

            if ($exam) {
                // Classes active in this exam's academic year
                $classIds = \App\Models\ClassSection::where('academic_year_id', $exam->academic_year_id)
                    ->distinct()->pluck('class_id');

                $classes = \App\Models\SchoolClass::whereIn('class_id', $classIds)
                    ->orderBy('numeric_value')->orderBy('name')
                    ->get(['class_id', 'name']);

                // Subjects actually mapped to those classes for the year
                $subjectIds = DB::table('class_subjects')
                    ->where('academic_year_id', $exam->academic_year_id)
                    ->whereIn('class_id', $classIds)
                    ->distinct()->pluck('subject_id');

                $subjects = Subject::whereIn('subject_id', $subjectIds)
                    ->orderBy('name')->get(['subject_id', 'name']);
            } else {
                $selectedExamId = null;
            }
        }

        return view('exam_schedules.auto_generate', compact(
            'exams', 'selectedExamId', 'classes', 'subjects'
        ));
    }

    /**
     * Auto-generate an exam timetable from the given exam parameters.
     *
     * Strategy: each subject gets its own session slot (all classes sitting
     * that subject at the same time, like a real national exam), sessions
     * spread across the exam window, rooms distributed round-robin.
     */
    public function storeAutoGenerated(Request $request)
    {
        $data = $request->validate([
            'exam_id'           => 'required|exists:exams,exam_id',
            'classes'           => 'nullable|array',
            'classes.*'         => 'integer',
            'subjects'          => 'nullable|array',
            'subjects.*'        => 'integer',
            'start_date'        => 'required|date',
            'sessions_per_day'  => 'required|in:1,2',
            'morning_start'     => 'required|date_format:H:i',
            'afternoon_start'   => 'nullable|required_if:sessions_per_day,2|date_format:H:i',
            'session_minutes'   => 'required|integer|min:30|max:360',
            'skip_weekends'     => 'nullable|boolean',
            'assign_rooms'      => 'nullable|boolean',
            'replace_existing'  => 'nullable|boolean',
            'max_marks'         => 'required|numeric|min:1|max:1000',
            'passing_marks'     => 'required|numeric|min:0|lte:max_marks',
        ]);

        $exam = Exam::findOrFail($data['exam_id']);

        // Classes that belong to this exam's academic year
        $classIds = \App\Models\ClassSection::where('academic_year_id', $exam->academic_year_id)
            ->distinct()->pluck('class_id');

        // Narrow to user-selected classes (if any were chosen)
        if (!empty($data['classes'])) {
            $classIds = $classIds->intersect($data['classes'])->values();
        }

        if ($classIds->isEmpty()) {
            Flash::error('No class sections exist for this exam\'s academic year.');
            return redirect()->back()->withInput();
        }

        // Subjects mapped to those classes for the year
        $mappings = DB::table('class_subjects')
            ->where('academic_year_id', $exam->academic_year_id)
            ->whereIn('class_id', $classIds);

        if (!empty($data['subjects'])) {
            $mappings->whereIn('subject_id', $data['subjects']);
        }

        $mappings = $mappings->get();

        if ($mappings->isEmpty()) {
            Flash::error('No subjects are mapped to the selected classes yet. Set up Class Subjects first.');
            return redirect()->back()->withInput();
        }

        // Subject => classes taking it
        $bySubject = $mappings->groupBy('subject_id');

        $rooms = \App\Models\Classroom::orderBy('classroom_id')->get();
        if ($data['assign_rooms'] && $rooms->isEmpty()) {
            $data['assign_rooms'] = false;
        }

        if (!empty($data['replace_existing'])) {
            ExamSchedule::where('exam_id', $exam->exam_id)->delete();
        }

        // Build session slots walking forward from start date
        $sessionMinutes = (int) $data['session_minutes'];
        $sessionsPerDay = (int) $data['sessions_per_day'];
        $skipWeekends   = !empty($data['skip_weekends']);

        $slots = [];
        $date = \Carbon\Carbon::parse($data['start_date']);
        $needed = count($bySubject);
        $guard = 0;

        while (count($slots) < $needed && $guard++ < 400) {
            if (!($skipWeekends && in_array($date->dayOfWeekIso, [6, 7]))) {
                $morning = \Carbon\Carbon::parse($date->toDateString() . ' ' . $data['morning_start']);
                $slots[] = [
                    'date' => $date->toDateString(),
                    'start' => $morning->format('H:i'),
                    'end' => $morning->copy()->addMinutes($sessionMinutes)->format('H:i'),
                ];

                if ($sessionsPerDay === 2 && count($slots) < $needed) {
                    $afternoon = \Carbon\Carbon::parse($date->toDateString() . ' ' . $data['afternoon_start']);
                    $slots[] = [
                        'date' => $date->toDateString(),
                        'start' => $afternoon->format('H:i'),
                        'end' => $afternoon->copy()->addMinutes($sessionMinutes)->format('H:i'),
                    ];
                }
            }
            $date->addDay();
        }

        $created = 0;
        $slotIndex = 0;

        foreach ($bySubject as $subjectId => $rows) {
            if ($slotIndex >= count($slots)) {
                break; // ran out of days within safety window
            }

            $slot = $slots[$slotIndex++];
            $roomIdx = 0;

            foreach ($rows as $row) {
                ExamSchedule::create([
                    'exam_id'           => $exam->exam_id,
                    'class_id'          => $row->class_id,
                    'subject_id'        => $subjectId,
                    'exam_date'         => $slot['date'],
                    'start_time'        => $slot['start'],
                    'end_time'          => $slot['end'],
                    'duration_minutes'  => $sessionMinutes,
                    'room_id'           => ($data['assign_rooms'] && $rooms->isNotEmpty())
                                            ? $rooms[$roomIdx++ % $rooms->count()]->classroom_id
                                            : null,
                    'max_marks'         => $data['max_marks'],
                    'passing_marks'     => $data['passing_marks'],
                ]);
                $created++;
            }
        }

        AuditTrail::log('Exam Schedule', 'AUTO_GENERATE', $exam->exam_id, null, [
            'sittings_created' => $created,
            'sessions_used' => min($slotIndex, count($slots)),
        ]);

        if ($created === 0) {
            Flash::error('Could not generate any sittings — not enough free days inside the safety window.');
            return redirect(route('exam-schedules.auto-generate'));
        }

        $daysUsed = collect($slots)->slice(0, $slotIndex)->pluck('date')->unique()->count();
        Flash::success("Exam timetable generated: {$created} sittings across {$daysUsed} day(s).");

        return redirect(route('exam-schedules.index', ['exam_id' => $exam->exam_id]));
    }

    /**
     * Store a newly created ExamSchedule in storage.
     */
    public function store(CreateExamScheduleRequest $request)
    {
        $input = $request->all();

        $examSchedule = $this->examScheduleRepository->create($input);

        AuditTrail::log('Exam Schedule', 'CREATE', $examSchedule->schedule_id, null, $examSchedule->toArray());

        Flash::success('Exam Schedule saved successfully.');

        return redirect(route('exam-schedules.index'));
    }

    /**
     * Display the specified ExamSchedule.
     */
    public function show($id)
    {
        $examSchedule = $this->examScheduleRepository->find($id);

        if (empty($examSchedule)) {
            Flash::error('Exam Schedule not found');

            return redirect(route('exam-schedules.index'));
        }

        return view('exam_schedules.show')->with('examSchedule', $examSchedule);
    }

    /**
     * Show the form for editing the specified ExamSchedule.
     */
    public function edit($id)
    {
        $examSchedule = $this->examScheduleRepository->find($id);
        $dropdownData = $this->getDropdownData();

        if (empty($examSchedule)) {
            Flash::error('Exam Schedule not found');

            return redirect(route('exam-schedules.index'));
        }

        return view('exam_schedules.edit', array_merge(['examSchedule' => $examSchedule], $dropdownData));
    }

    /**
     * Update the specified ExamSchedule in storage.
     */
    public function update($id, UpdateExamScheduleRequest $request)
    {
        $examSchedule = $this->examScheduleRepository->find($id);

        if (empty($examSchedule)) {
            Flash::error('Exam Schedule not found');

            return redirect(route('exam-schedules.index'));
        }

        $oldData = $examSchedule->toArray();
        $examSchedule = $this->examScheduleRepository->update($request->all(), $id);

        AuditTrail::log('Exam Schedule', 'UPDATE', $examSchedule->schedule_id, $oldData, $examSchedule->toArray());

        Flash::success('Exam Schedule updated successfully.');

        return redirect(route('exam-schedules.index'));
    }

    /**
     * Remove the specified ExamSchedule from storage.
     *
     * @throws \Exception
     */
    public function destroy($id)
    {
        $examSchedule = $this->examScheduleRepository->find($id);

        if (empty($examSchedule)) {
            Flash::error('Exam Schedule not found');

            return redirect(route('exam-schedules.index'));
        }

        $oldData = $examSchedule->toArray();
        $this->examScheduleRepository->delete($id);

        AuditTrail::log('Exam Schedule', 'DELETE', $id, $oldData, null);

        Flash::success('Exam Schedule deleted successfully.');

        return redirect(route('exam-schedules.index'));
    }
}
