<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTimetableRequest;
use App\Http\Requests\UpdateTimetableRequest;
use App\Http\Controllers\AppBaseController;
use App\Repositories\TimetableRepository;
use App\Models\ClassSection;
use App\Models\ClassSubject;
use App\Models\Period;
use App\Models\Subject;
use App\Models\Staff;
use App\Models\Classroom;
use App\Models\AcademicYear;
use App\Models\AuditTrail;
use App\Models\Timetable;
use App\Models\TermWeek;
use App\Models\TimetableOverride;
use App\Services\TimetableGeneratorService;
use App\Services\TimetableGenerationResult;
use App\Services\TimetableConflictService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Flash;

class TimetableController extends AppBaseController
{
    /** @var TimetableRepository $timetableRepository*/
    private $timetableRepository;

    public function __construct(TimetableRepository $timetableRepo)
    {
        $this->timetableRepository = $timetableRepo;

        $this->middleware('auth');
        $this->middleware('can:academics.view')->only(['index', 'show', 'autoGenerate']);
        $this->middleware('can:academics.settings.manage')->only(['create', 'store', 'edit', 'update', 'destroy', 'storeAutoGenerated', 'saveAutoGenerateOptions']);
    }

    /**
     * Display a listing of the Timetable.
     */
    public function index(Request $request)
    {
        $academicYears = AcademicYear::orderBy('start_date', 'desc')->get();

        $selectedAcademicYearId = $request->get('academic_year_id');
        if (!$selectedAcademicYearId && $academicYears->count() > 0) {
            $current = $academicYears->firstWhere('is_current', true);
            $selectedAcademicYearId = $current ? $current->academic_year_id : $academicYears->first()->academic_year_id;
        }

        $classSections = collect();
        $selectedClassSectionId = $request->get('class_section_id');
        $timetables = collect();
        $periods = collect();

        $daysOfWeek = [
            'monday' => 'Monday',
            'tuesday' => 'Tuesday',
            'wednesday' => 'Wednesday',
            'thursday' => 'Thursday',
            'friday' => 'Friday',
            'saturday' => 'Saturday',
            'sunday' => 'Sunday',
        ];

        if ($selectedAcademicYearId) {
            $classSections = ClassSection::with(['class', 'section'])
                ->where('academic_year_id', $selectedAcademicYearId)
                ->orderBy('class_id')
                ->orderBy('section_id')
                ->get();

            if (!$selectedClassSectionId && $classSections->count() > 0) {
                $selectedClassSectionId = $classSections->first()->class_section_id;
            }

            if ($selectedClassSectionId) {
                $timetables = $this->timetableRepository
                    ->with([
                        'classSection.class',
                        'classSection.section',
                        'period',
                        'subject',
                        'teacher',
                        'classroom',
                        'academicYear',
                    ])
                    ->where('academic_year_id', $selectedAcademicYearId)
                    ->where('class_section_id', $selectedClassSectionId)
                    ->get();

                $periods = Period::orderBy('start_time')->get();
            }
        }

        $academicYearOptions = $academicYears->pluck('name', 'academic_year_id');

        $classSectionOptions = $classSections->mapWithKeys(function ($item) {
            $className = $item->class->name ?? '';
            $sectionName = $item->section->name ?? '';
            $parts = array_filter([$className, $sectionName]);
            $label = count($parts) ? implode(' - ', $parts) : 'Section ' . $item->class_section_id;
            return [$item->class_section_id => $label];
        });

        $schedule = [];
        foreach ($timetables as $entry) {
            $day = $entry->day_of_week;
            $periodId = $entry->period_id;
            if (!isset($schedule[$day])) {
                $schedule[$day] = [];
            }
            $schedule[$day][$periodId] = $entry;
        }

        return view('timetables.index', [
            'timetables' => $timetables,
            'academicYearOptions' => $academicYearOptions,
            'classSectionOptions' => $classSectionOptions,
            'selectedAcademicYearId' => $selectedAcademicYearId,
            'selectedClassSectionId' => $selectedClassSectionId,
            'periods' => $periods,
            'daysOfWeek' => $daysOfWeek,
            'schedule' => $schedule,
        ]);
    }

    /**
     * Show the form for creating a new Timetable.
     */
    public function create()
    {
        $data = $this->getFormData();
        return view('timetables.create', $data);
    }

    /**
     * Store a newly created Timetable in storage.
     */
    public function store(CreateTimetableRequest $request)
    {
        $input = $request->all();
        $timetable = $this->timetableRepository->create($input);
        AuditTrail::log('Timetable', 'CREATE', $timetable->timetable_id, null, $timetable->toArray());
        Flash::success('Timetable saved successfully.');
        return redirect(route('timetables.index'));
    }

    /**
     * Display the specified Timetable.
     */
    public function show($id)
    {
        $timetable = $this->timetableRepository->with([
            'classSection.class',
            'classSection.section',
            'period',
            'subject',
            'teacher',
            'classroom',
            'academicYear'
        ])->find($id);

        if (empty($timetable)) {
            Flash::error('Timetable not found');
            return redirect(route('timetables.index'));
        }

        return view('timetables.show')->with('timetable', $timetable);
    }

    /**
     * Show the form for editing the specified Timetable.
     */
    public function edit($id)
    {
        $timetable = $this->timetableRepository->find($id);

        if (empty($timetable)) {
            Flash::error('Timetable not found');
            return redirect(route('timetables.index'));
        }

        $data = $this->getFormData();
        $data['timetable'] = $timetable;

        return view('timetables.edit', $data);
    }

    /**
     * Update the specified Timetable in storage.
     */
    public function update($id, UpdateTimetableRequest $request)
    {
        $timetable = $this->timetableRepository->find($id);

        if (empty($timetable)) {
            Flash::error('Timetable not found');
            return redirect(route('timetables.index'));
        }

        $oldData = $timetable->toArray();
        $timetable = $this->timetableRepository->update($request->all(), $id);
        AuditTrail::log('Timetable', 'UPDATE', $timetable->timetable_id, $oldData, $timetable->toArray());
        Flash::success('Timetable updated successfully.');
        return redirect(route('timetables.index'));
    }

    /**
     * Remove the specified Timetable from storage.
     */
    public function destroy($id)
    {
        $timetable = $this->timetableRepository->find($id);

        if (empty($timetable)) {
            Flash::error('Timetable not found');
            return redirect(route('timetables.index'));
        }

        $oldData = $timetable->toArray();
        $this->timetableRepository->delete($id);
        AuditTrail::log('Timetable', 'DELETE', $id, $oldData, null);
        Flash::success('Timetable deleted successfully.');
        return redirect(route('timetables.index'));
    }

    /**
     * Ordered day-of-week labels shared by the teacher timetable view.
     */
    protected static function daysOfWeek(): array
    {
        return [
            'monday' => 'Monday',
            'tuesday' => 'Tuesday',
            'wednesday' => 'Wednesday',
            'thursday' => 'Thursday',
            'friday' => 'Friday',
            'saturday' => 'Saturday',
            'sunday' => 'Sunday',
        ];
    }

    /**
     * Display the teacher's personal timetable.
     */
    public function teacherTimetable(Request $request)
    {
        $user = auth()->user();
        $staff = Staff::where('user_id', $user->id)->first();
        
        // Allow admin/principal to select a teacher to view
        $selectedStaffId = $request->get('staff_id');
        $allTeachers = collect();

        // Check permissions
        $isAdmin = $user->hasAnyRole(['Super Admin', 'Admin']);

        if ($isAdmin) {
            $allTeachers = Staff::where('staff_type', 'teaching')
                ->active()
                ->orderBy('first_name')
                ->get();
            
            if (!$selectedStaffId && $allTeachers->isNotEmpty()) {
                $selectedStaffId = $staff ? $staff->staff_id : $allTeachers->first()->staff_id;
            }
        } else {
            if (!$staff) {
                Flash::error('You are not registered as a staff member. Contact your administrator.');
                return view('timetables.teacher_timetable', [
                    'staff' => null,
                    'viewingStaff' => null,
                    'allTeachers' => collect(),
                    'timetables' => collect(),
                    'periods' => collect(),
                    'daysOfWeek' => self::daysOfWeek(),
                    'schedule' => [],
                    'academicYearOptions' => ['' => 'Select Year'],
                    'selectedAcademicYearId' => null,
                    'todayClasses' => collect(),
                    'assignments' => collect(),
                    'isAdmin' => false,
                ]);
            }
            $selectedStaffId = $staff->staff_id;
        }

        $viewingStaff = Staff::with('department')->find($selectedStaffId);

        $academicYears = AcademicYear::orderBy('start_date', 'desc')->get();
        $selectedAcademicYearId = $request->get('academic_year_id');
        
        if (!$selectedAcademicYearId && $academicYears->count() > 0) {
            $current = $academicYears->firstWhere('is_current', true);
            $selectedAcademicYearId = $current ? $current->academic_year_id : $academicYears->first()->academic_year_id;
        }

        $timetables = $this->timetableRepository->with([
            'classSection.class',
            'classSection.section',
            'period',
            'subject',
            'classroom',
            'academicYear',
        ])
        ->where('teacher_id', $selectedStaffId)
        ->where('academic_year_id', $selectedAcademicYearId)
        ->get();

        $periods = Period::orderBy('start_time')->get();
        $daysOfWeek = self::daysOfWeek();

        $schedule = [];
        foreach ($timetables as $entry) {
            $day = $entry->day_of_week;
            $periodId = $entry->period_id;
            if (!isset($schedule[$day])) {
                $schedule[$day] = [];
            }
            $schedule[$day][$periodId] = $entry;
        }

        // Today's classes
        $today = strtolower(now()->format('l'));
        $todayClasses = $timetables->where('day_of_week', $today)->sortBy(function($t) {
            return $t->period->start_time;
        });

        // Subject Assignment Summary
        $assignments = \App\Models\TeacherSubject::with(['subject', 'classSection.class', 'classSection.section'])
            ->where('staff_id', $selectedStaffId)
            ->where('academic_year_id', $selectedAcademicYearId)
            ->get();

        return view('timetables.teacher_timetable', [
            'staff' => $staff,
            'viewingStaff' => $viewingStaff,
            'allTeachers' => $allTeachers,
            'timetables' => $timetables,
            'periods' => $periods,
            'daysOfWeek' => $daysOfWeek,
            'schedule' => $schedule,
            'academicYearOptions' => $academicYears->pluck('name', 'academic_year_id'),
            'selectedAcademicYearId' => $selectedAcademicYearId,
            'todayClasses' => $todayClasses,
            'assignments' => $assignments,
            'isAdmin' => $isAdmin
        ]);
    }

    /**
     * Get class sections for a specific academic year (AJAX)
     */
    public function getClassSectionsByYear(Request $request, $academicYearId)
    {
        if (!$academicYearId) {
            return response()->json([]);
        }

        $classSections = ClassSection::with(['class', 'section'])
            ->where('academic_year_id', $academicYearId)
            ->orderBy('class_id')
            ->orderBy('section_id')
            ->get()
            ->map(function ($item) {
                $className   = $item->class->name ?? '';
                $sectionName = $item->section->name ?? '';
                $parts       = array_filter([$className, $sectionName]);
                $label       = count($parts)
                    ? implode(' - ', $parts)
                    : 'Section ' . $item->class_section_id;

                return [
                    'id'    => $item->class_section_id,
                    'label' => $label,
                ];
            });

        return response()->json($classSections);
    }


    /**
     * Get teachers for a specific subject (AJAX).
     * Deduplicates staff across multiple class-section assignments for the same subject.
     * Optionally narrows by class_section_id and/or academic_year_id query params.
     */
    public function getTeachersBySubject(Request $request, $subjectId)
    {
        $classSectionId  = $request->get('class_section_id');
        $academicYearId  = $request->get('academic_year_id');

        $query = \App\Models\TeacherSubject::with('staff')
            ->where('subject_id', $subjectId);

        if ($classSectionId) {
            $query->where('class_section_id', $classSectionId);
        }

        if ($academicYearId) {
            $query->where('academic_year_id', $academicYearId);
        }

        // Deduplicate by staff_id so one teacher appearing in multiple rows shows only once
        $teachers = $query->get()
            ->filter(fn($item) => $item->staff !== null)
            ->unique('staff_id')
            ->map(function ($item) {
                $staff = $item->staff;
                $name  = trim(
                    $staff->first_name . ' ' .
                    ($staff->middle_name ? $staff->middle_name . ' ' : '') .
                    $staff->last_name
                );
                if ($staff->employee_id) {
                    $name .= ' (' . $staff->employee_id . ')';
                }
                return ['id' => $staff->staff_id, 'name' => $name];
            })
            ->values(); // re-index to a clean JSON array

        return response()->json($teachers);
    }

    /**
     * Preview an auto-generated weekly timetable for one academic year.
     * Nothing is saved here — the admin must confirm via storeAutoGenerated.
     */
    public function autoGenerate(Request $request)
    {
        $academicYears = AcademicYear::orderBy('start_date', 'desc')->get();

        $selectedAcademicYearId = $request->get('academic_year_id');
        if (!$selectedAcademicYearId && $academicYears->count() > 0) {
            $current = $academicYears->firstWhere('is_current', true);
            $selectedAcademicYearId = $current ? $current->academic_year_id : $academicYears->first()->academic_year_id;
        }

        $classSubjectOptions = collect();
        if ($selectedAcademicYearId) {
            $classSubjectOptions = ClassSubject::with(['class', 'subject.department'])
                ->where('academic_year_id', $selectedAcademicYearId)
                ->orderBy('class_id')
                ->orderBy('subject_id')
                ->get();
        }

        $preview = null;
        $result = null;

        if ($selectedAcademicYearId && $request->boolean('preview')) {
            $result = $this->generateTimetable((int) $selectedAcademicYearId);
            $preview = $this->buildPreview($result, (int) $selectedAcademicYearId);
        }

        return view('timetables.auto_generate', [
            'academicYears' => $academicYears,
            'academicYearOptions' => $academicYears->pluck('name', 'academic_year_id'),
            'selectedAcademicYearId' => $selectedAcademicYearId,
            'classSubjectOptions' => $classSubjectOptions,
            'result' => $result,
            'preview' => $preview,
        ]);
    }

    /**
     * Persist per-subject weekly period counts for an academic year, then
     * regenerate the preview so the admin can review before confirming.
     */
    public function saveAutoGenerateOptions(Request $request)
    {
        $academicYearId = (int) $request->input('academic_year_id');
        $periods = $request->input('periods', []); // [class_subject_id => count]

        foreach ($periods as $id => $count) {
            $classSubject = ClassSubject::where('academic_year_id', $academicYearId)->find($id);
            if (!$classSubject) {
                continue;
            }
            $classSubject->periods_per_week = max(1, min(40, (int) $count));
            $classSubject->save();
        }

        Flash::success('Weekly period settings saved. Review the preview below, then confirm.');
        return redirect(route('timetables.auto-generate', [
            'academic_year_id' => $academicYearId,
            'preview' => 1,
        ]));
    }

    /**
     * Persist a previously-previewed auto-generated timetable.
     * Regenerates server-side (never trusts the client), replaces the
     * academic year's lessons within a transaction, validates each row
     * through the model, and audits the change. Also auto-generates
     * term weeks if none exist yet.
     */
    public function storeAutoGenerated(Request $request)
    {
        $academicYearId = (int) $request->input('academic_year_id');

        $academicYear = AcademicYear::find($academicYearId);
        if (!$academicYear) {
            Flash::error('Academic year not found.');
            return redirect(route('timetables.auto-generate'));
        }

        $result = $this->generateTimetable($academicYearId);

        if ($result->placedCount() === 0) {
            Flash::warning('Auto-generation produced no lessons. Check that periods, class sections, subjects and teacher assignments exist.');
            return redirect(route('timetables.auto-generate', ['academic_year_id' => $academicYearId]));
        }

        // Auto-generate term weeks if none exist for this academic year
        $existingWeekCount = TermWeek::where('academic_year_id', $academicYearId)->count();
        if ($existingWeekCount === 0) {
            $this->generateTermWeeksForYear($academicYearId);
        }

        $oldData = Timetable::where('academic_year_id', $academicYearId)->get()->toArray();
        $savedCount = 0;
        $validationErrors = [];

        DB::transaction(function () use ($academicYearId, $result, &$savedCount, &$validationErrors) {
            Timetable::where('academic_year_id', $academicYearId)->delete();

            foreach ($result->placements as $idx => $row) {
                // Validate through the model before inserting
                $timetable = new Timetable();
                $timetable->fill($row);

                $validator = \Illuminate\Support\Facades\Validator::make(
                    $timetable->toArray(),
                    [
                        'class_section_id' => 'required|exists:class_sections,class_section_id',
                        'day_of_week' => 'required|string|in:monday,tuesday,wednesday,thursday,friday,saturday,sunday',
                        'period_id' => 'required|exists:periods,period_id',
                        'subject_id' => 'required|exists:subjects,subject_id',
                        'teacher_id' => 'required|exists:staff,staff_id',
                        'classroom_id' => 'required|exists:classrooms,classroom_id',
                        'academic_year_id' => 'required|exists:academic_years,academic_year_id',
                    ]
                );

                if ($validator->fails()) {
                    $validationErrors[] = "Row " . ($idx + 1) . ": " . $validator->errors()->first();
                    continue;
                }

                $timetable->save();
                $savedCount++;
            }
        });

        AuditTrail::log('Timetable', 'AUTO_GENERATE', null, $oldData, [
            'academic_year_id' => $academicYearId,
            'placed' => $savedCount,
            'unplaced' => $result->unplaced,
            'validation_errors' => $validationErrors,
        ]);

        $messages = [];
        if ($savedCount > 0) {
            $messages[] = $savedCount . ' lessons generated successfully.';
        }
        if ($result->unplacedCount() > 0) {
            $messages[] = $result->unplacedCount() . ' could not be placed (see details).';
        }
        if (!empty($validationErrors)) {
            $messages[] = count($validationErrors) . ' rows had validation errors.';
        }

        Flash::warning(implode(' ', $messages) ?: 'No lessons were generated.');

        return redirect(route('timetables.index', ['academic_year_id' => $academicYearId]));
    }

    /**
     * Auto-generate term weeks for all terms in an academic year.
     */
    private function generateTermWeeksForYear(int $academicYearId): void
    {
        $terms = \App\Models\Term::where('academic_year_id', $academicYearId)->get();
        foreach ($terms as $term) {
            $weeks = TermWeek::generateForTerm($term);
            foreach ($weeks as $weekData) {
                TermWeek::create($weekData);
            }
        }
    }

    /**
     * AJAX: Check for conflicts when assigning a teacher/classroom to a slot.
     * Reuses TimetableConflictService directly — no duplicated logic.
     */
    public function checkConflict(Request $request)
    {
        $request->validate([
            'academic_year_id' => 'required|integer|exists:academic_years,academic_year_id',
            'term_week_id' => 'required|integer|exists:term_weeks,id',
            'teacher_id' => 'required|integer|exists:staff,staff_id',
            'day_of_week' => 'required|string|in:monday,tuesday,wednesday,thursday,friday,saturday,sunday',
            'period_id' => 'required|integer|exists:periods,period_id',
            'class_section_id' => 'nullable|integer|exists:class_sections,class_section_id',
            'classroom_id' => 'nullable|integer|exists:classrooms,classroom_id',
            'ignore_timetable_id' => 'nullable|integer',
        ]);

        $academicYearId = (int) $request->input('academic_year_id');
        $termWeekId = (int) $request->input('term_week_id');
        $teacherId = (int) $request->input('teacher_id');
        $day = $request->input('day_of_week');
        $periodId = (int) $request->input('period_id');
        $ignoreId = $request->input('ignore_timetable_id') ? (int) $request->input('ignore_timetable_id') : null;

        $conflicts = [];
        $warnings = [];

        // Teacher conflict on effective schedule
        $teacherResult = TimetableConflictService::effectiveTeacherConflict(
            $academicYearId, $termWeekId, $teacherId, $day, $periodId, $ignoreId
        );
        if ($teacherResult) {
            $conflicts['teacher'] = $teacherResult;
        }

        // Class slot conflict
        $classSectionId = $request->input('class_section_id');
        if ($classSectionId) {
            $classResult = TimetableConflictService::effectiveClassSlotTaken(
                $academicYearId, $termWeekId, (int) $classSectionId, $day, $periodId, $ignoreId
            );
            if ($classResult) {
                $conflicts['class_section'] = $classResult;
            }
        }

        // Classroom conflict
        $classroomId = $request->input('classroom_id');
        if ($classroomId) {
            $roomResult = TimetableConflictService::effectiveClassroomConflict(
                $academicYearId, $termWeekId, (int) $classroomId, $day, $periodId, $ignoreId
            );
            if ($roomResult) {
                $conflicts['classroom'] = $roomResult;
            }
        }

        // Teacher workload warnings
        $workloadWarnings = TimetableConflictService::checkTeacherWorkload(
            $teacherId, $academicYearId, $day, $ignoreId
        );
        if (!empty($workloadWarnings)) {
            $warnings['workload'] = $workloadWarnings;
        }

        return response()->json([
            'has_conflicts' => !empty($conflicts),
            'conflicts' => $conflicts,
            'warnings' => $warnings,
        ]);
    }

    /**
     * Store timetable overrides (cancel/substitute/reschedule) for a term week.
     */
    public function storeOverrides(Request $request)
    {
        $request->validate([
            'academic_year_id' => 'required|integer|exists:academic_years,academic_year_id',
            'term_week_id' => 'required|integer|exists:term_weeks,id',
            'overrides' => 'required|array|min:1',
            'overrides.*.timetable_id' => 'required|integer|exists:timetable,timetable_id',
            'overrides.*.override_type' => 'required|in:cancel,substitute,reschedule',
            'overrides.*.substitute_teacher_id' => 'nullable|exists:staff,staff_id',
            'overrides.*.substitute_classroom_id' => 'nullable|exists:classrooms,classroom_id',
            'overrides.*.new_day_of_week' => 'nullable|string|in:monday,tuesday,wednesday,thursday,friday,saturday,sunday',
            'overrides.*.new_period_id' => 'nullable|exists:periods,period_id',
            'overrides.*.new_teacher_id' => 'nullable|exists:staff,staff_id',
            'overrides.*.new_classroom_id' => 'nullable|exists:classrooms,classroom_id',
            'overrides.*.effective_date' => 'required|date',
            'overrides.*.reason' => 'nullable|string|max:255',
        ]);

        $academicYearId = (int) $request->input('academic_year_id');
        $termWeekId = (int) $request->input('term_week_id');
        $overrides = $request->input('overrides');
        $saved = 0;
        $errors = [];

        foreach ($overrides as $idx => $ov) {
            // Validate conditional reason requirement
            if (in_array($ov['override_type'], ['cancel', 'reschedule']) && empty($ov['reason'])) {
                $errors[] = "Override #" . ($idx + 1) . ": reason is required for {$ov['override_type']} overrides.";
                continue;
            }

            // Check for existing override on this timetable_id + term_week_id
            $existing = TimetableOverride::where('timetable_id', $ov['timetable_id'])
                ->where('term_week_id', $termWeekId)
                ->first();

            if ($existing) {
                $existing->update(array_merge($ov, [
                    'created_by' => auth()->id(),
                ]));
            } else {
                TimetableOverride::create(array_merge($ov, [
                    'created_by' => auth()->id(),
                ]));
            }
            $saved++;
        }

        if ($request->ajax() || $request->wantsJson()) {
            if (!empty($errors)) {
                return response()->json(['saved' => $saved, 'errors' => $errors], 422);
            }
            return response()->json(['saved' => $saved, 'message' => "Saved {$saved} override(s) for the selected week."]);
        }

        if (!empty($errors)) {
            Flash::warning("Saved {$saved} override(s). Issues: " . implode(' ', $errors));
        } else {
            Flash::success("Saved {$saved} override(s) for the selected week.");
        }

        return redirect()->back();
    }

    /**
     * Get term weeks for an academic year (AJAX).
     */
    public function getTermWeeks(Request $request, int $academicYearId)
    {
        $weeks = TermWeek::where('academic_year_id', $academicYearId)
            ->with('term')
            ->orderBy('term_id')
            ->orderBy('week_number')
            ->get()
            ->map(fn($w) => [
                'id' => $w->id,
                'week_number' => $w->week_number,
                'label' => $w->label,
                'start_date' => $w->start_date->format('Y-m-d'),
                'end_date' => $w->end_date->format('Y-m-d'),
                'is_exam_week' => $w->is_exam_week,
                'is_half_term' => $w->is_half_term,
                'term_name' => $w->term->name ?? '',
            ]);

        return response()->json($weeks);
    }

    /**
     * Get overrides for a specific term week (AJAX).
     */
    public function getOverrides(Request $request, int $termWeekId)
    {
        $overrides = TimetableOverride::where('term_week_id', $termWeekId)
            ->with(['timetable.subject', 'timetable.teacher', 'timetable.classSection.class', 'timetable.classSection.section', 'newPeriod', 'newTeacher'])
            ->get()
            ->map(fn($ov) => [
                'id' => $ov->id,
                'timetable_id' => $ov->timetable_id,
                'override_type' => $ov->override_type,
                'reason' => $ov->reason,
                'effective_date' => $ov->effective_date->format('Y-m-d'),
                'timetable' => [
                    'subject' => $ov->timetable->subject->name ?? 'Subject',
                    'teacher' => trim(($ov->timetable->teacher->first_name ?? '') . ' ' . ($ov->timetable->teacher->last_name ?? '')),
                    'day_of_week' => $ov->timetable->day_of_week,
                    'period' => $ov->timetable->period->name ?? '',
                    'class_section' => trim(($ov->timetable->classSection->class->name ?? '') . ' - ' . ($ov->timetable->classSection->section->name ?? '')),
                ],
                'substitute_teacher' => $ov->substituteTeacher ? trim($ov->substituteTeacher->first_name . ' ' . $ov->substituteTeacher->last_name) : null,
                'new_day_of_week' => $ov->new_day_of_week,
                'new_period' => $ov->newPeriod ? $ov->newPeriod->name : null,
                'new_teacher' => $ov->newTeacher ? trim($ov->newTeacher->first_name . ' ' . $ov->newTeacher->last_name) : null,
            ]);

        return response()->json($overrides);
    }

    /**
     * Get all teachers (AJAX) for override modal dropdowns.
     */
    public function getTeachers(Request $request)
    {
        $teachers = Staff::where('staff_type', 'teaching')
            ->active()
            ->orderBy('first_name')
            ->get()
            ->map(fn($s) => [
                'id' => $s->staff_id,
                'name' => trim($s->first_name . ' ' . $s->middle_name . ' ' . $s->last_name),
            ]);

        return response()->json($teachers);
    }

    /**
     * Get all periods (AJAX) for override modal dropdowns.
     */
    public function getPeriods(Request $request)
    {
        $periods = Period::where('type', 'period')
            ->orderBy('start_time')
            ->get()
            ->map(fn($p) => [
                'id' => $p->period_id,
                'name' => $p->name,
            ]);

        return response()->json($periods);
    }

    /**
     * Assemble the pure-array input for the generator from the database.
     */
    private function generateTimetable(int $academicYearId): TimetableGenerationResult
    {
        $classSections = ClassSection::with(['class', 'section'])
            ->where('academic_year_id', $academicYearId)
            ->orderBy('class_id')
            ->orderBy('section_id')
            ->get();

        $periods = Period::where('type', 'period')
            ->orderBy('start_time')
            ->get(['period_id', 'start_time', 'name']);

        $classSubjects = ClassSubject::where('academic_year_id', $academicYearId)->get()->toArray();
        $teacherSubjects = \App\Models\TeacherSubject::where('academic_year_id', $academicYearId)->get()->toArray();

        $subjects = \App\Models\Subject::pluck('name', 'subject_id')->toArray();
        $teachers = \App\Models\Staff::where('staff_type', 'teaching')
            ->active()
            ->get()
            ->mapWithKeys(function ($staff) {
                return [$staff->staff_id => trim($staff->first_name . ' ' . $staff->middle_name . ' ' . $staff->last_name)];
            })
            ->toArray();
        $classrooms = \App\Models\Classroom::pluck('room_number', 'classroom_id')->toArray();

        $existing = Timetable::where('academic_year_id', $academicYearId)->get()->toArray();

        $service = new TimetableGeneratorService();

        return $service->generate([
            'academic_year_id' => $academicYearId,
            'class_sections' => $classSections->map(function ($cs) {
                return [
                    'id' => $cs->class_section_id,
                    'class_id' => $cs->class_id,
                    'classroom_id' => $cs->classroom_id,
                    'label' => trim(($cs->class->name ?? '') . ' - ' . ($cs->section->name ?? '')),
                ];
            })->values()->toArray(),
            'periods' => $periods->map(function ($period) {
                return ['id' => $period->period_id, 'start_time' => $period->start_time, 'name' => $period->name];
            })->values()->toArray(),
            'class_subjects' => $classSubjects,
            'teacher_subjects' => $teacherSubjects,
            'subjects' => $subjects,
            'teachers' => $teachers,
            'classrooms' => $classrooms,
            'existing' => $existing,
        ]);
    }

    /**
     * Build per-class-section weekly grids for the preview view.
     */
    private function buildPreview(TimetableGenerationResult $result, int $academicYearId): array
    {
        $periods = Period::where('type', 'period')->orderBy('start_time')->get(['period_id', 'name', 'start_time']);
        $daysOfWeek = [
            'monday' => 'Monday',
            'tuesday' => 'Tuesday',
            'wednesday' => 'Wednesday',
            'thursday' => 'Thursday',
            'friday' => 'Friday',
            'saturday' => 'Saturday',
            'sunday' => 'Sunday',
        ];

        $subjectNames = \App\Models\Subject::pluck('name', 'subject_id');
        $teacherNames = \App\Models\Staff::all()->mapWithKeys(function ($staff) {
            return [$staff->staff_id => trim($staff->first_name . ' ' . $staff->last_name)];
        });
        $classroomNumbers = \App\Models\Classroom::pluck('room_number', 'classroom_id');
        $sectionLabels = ClassSection::with(['class', 'section'])
            ->where('academic_year_id', $academicYearId)
            ->get()
            ->mapWithKeys(function ($cs) {
                return [$cs->class_section_id => trim(($cs->class->name ?? '') . ' - ' . ($cs->section->name ?? ''))];
            });

        $schedules = [];
        foreach ($result->placements as $row) {
            $csId = (int) $row['class_section_id'];
            if (!isset($schedules[$csId])) {
                $schedules[$csId] = [
                    'label' => $sectionLabels[$csId] ?? 'Section #' . $csId,
                    'grid' => [],
                ];
            }
            $schedules[$csId]['grid'][$row['day_of_week']][(int) $row['period_id']] = [
                'subject' => $subjectNames[$row['subject_id']] ?? 'Subject #' . $row['subject_id'],
                'teacher' => $teacherNames[$row['teacher_id']] ?? 'Teacher #' . $row['teacher_id'],
                'classroom' => $classroomNumbers[$row['classroom_id']] ?? 'Room',
            ];
        }

        return [
            'periods' => $periods,
            'daysOfWeek' => $daysOfWeek,
            'schedules' => $schedules,
        ];
    }

    /**
     * Get data needed for create/edit forms
     */
    private function getFormData(): array
    {
        return [
            'classSections' => ClassSection::with(['class', 'section', 'academicYear'])
                ->get()
                ->mapWithKeys(function ($item) {
                    $className = $item->class->name ?? 'Unknown Class';
                    $sectionName = $item->section->name ?? 'Unknown Section';
                    return [$item->class_section_id => $className . ' - ' . $sectionName];
                })
                ->toArray(),

            'periods' => Period::where('type', 'period')
                ->orderBy('start_time')
                ->pluck('name', 'period_id')
                ->toArray(),

            'subjects' => Subject::orderBy('name')
                ->pluck('name', 'subject_id')
                ->toArray(),

            'teachers' => Staff::where('staff_type', 'teaching')
                ->active()
                ->orderBy('first_name')
                ->get()
                ->mapWithKeys(function ($staff) {
                    $name = trim($staff->first_name . ' ' . $staff->middle_name . ' ' . $staff->last_name);
                    if ($staff->employee_id) {
                        $name .= ' (' . $staff->employee_id . ')';
                    }
                    return [$staff->staff_id => $name];
                })
                ->toArray(),

            'classrooms' => Classroom::pluck('room_number', 'classroom_id')
                ->toArray(),

            'academicYears' => AcademicYear::orderBy('start_date', 'desc')
                ->pluck('name', 'academic_year_id')
                ->toArray(),

            'daysOfWeek' => [
                'monday' => 'Monday',
                'tuesday' => 'Tuesday',
                'wednesday' => 'Wednesday',
                'thursday' => 'Thursday',
                'friday' => 'Friday',
                'saturday' => 'Saturday',
                'sunday' => 'Sunday'
            ]
        ];
    }
}
